# Generated by Django 5.1.15 on 2026-02-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_productcache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
